export default {
  GET_STOCK_SYMBOLES: 'GET_STOCK_SYMBOLES',
  GET_STOCK_SYMBOLES_PENDING: 'GET_STOCK_SYMBOLES_PENDING',
  GET_STOCK_SYMBOLES_SUCCESS: 'GET_STOCK_SYMBOLES_SUCCESS',
  GET_STOCK_SYMBOLES_ERROR: 'GET_STOCK_SYMBOLES_ERROR',
  SELECT_SITE_FOR_SYA: 'SELECT_SITE_FOR_SYA',
  GET_QUERIES_FOR_SYA: 'GET_QUERIES_FOR_SYA',
  CLEAR_QUERY_DATA: 'CLEAR_QUERY_DATA',
  SECURE_YOUR_ACCOUNT_LOADING: 'SECURE_YOUR_ACCOUNT_LOADING',
  SECURE_YOUR_ACCOUNT_SUCCESS: 'SECURE_YOUR_ACCOUNT_SUCCESS',
  SECURE_YOUR_ACCOUNT_ERROR: 'SECURE_YOUR_ACCOUNT_ERROR',



  REFRESH_DATA: 'REFRESH_DATA',
  CLEAR_MEMBER_LIST: 'CLEAR_MEMBER_LIST',
  GET_SANJI_DATA: 'GET_SANJI_DATA',
  GET_JANOI_DATA: 'GET_JANOI_DATA',
  GET_KANKOTRI_DATA: 'GET_KANKOTRI_DATA',
  GET_JAAN_DATA: 'GET_JAAN_DATA',
};


